basePath: /api/v1
host: localhost
info:
  contact:
    email: jhj377@gmail.com
    name: Hojin Jang
    url: https://github.com/hojin-kr
  description: This is a game server basic.
  title: Game Server Basic API
  version: "1.0"
paths:
  /accounts/get:
    post:
      consumes:
      - application/json
      description: get or Register account by ID, ID에 -1을 넘기면 계정 생성
      parameters:
      - description: Account ID
        in: query
        name: ID
        required: true
        type: integer
      responses:
        "200":
          description: ok
          schema:
            type: Account
      summary: get an account
      tags:
      - accounts
  /profiles/get:
    post:
      consumes:
      - application/json
      description: get profile by ID
      parameters:
      - description: Account ID
        in: query
        name: ID
        required: true
        type: integer
      responses:
        "200":
          description: ok
          schema:
            type: Profile
      summary: get an profile
      tags:
      - profiles
  /profiles/set:
    post:
      consumes:
      - application/json
      description: set profile by ID
      parameters:
      - description: Account ID
        in: query
        name: ID
        required: true
        type: integer
      - description: Nickname
        in: query
        name: Nickname
        required: true
        type: string
      responses:
        "200":
          description: ok
          schema:
            type: Profile
      summary: set an profile
      tags:
      - profiles
swagger: "2.0"
