apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: golf
  annotations:
    run.googleapis.com/ingress: all
spec:
  template:
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      serviceAccountName: golf-367911@appspot.gserviceaccount.com
      containers:
      - image: gcr.io/golf-367911/haru:0.1.9
        ports:
        - name: h2c
          containerPort: 50051
        env:
        - name: PROJECT_ID
          value: golf-367911
        - name: APP_KEY
          value: ""
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi