apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: golf
  annotations:
    run.googleapis.com/ingress: all
spec:
  template:
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      serviceAccountName: golf-367911@appspot.gserviceaccount.com
      containers:
      - image: gcr.io/${PROJECT_ID}/${SERVICE_NAME}:${VERSION}
        ports:
        - name: h2c
          containerPort: 50051
        env:
        - name: APP_ENVIRONMENT
          value: ${APP_ENVIRONMENT}
        - name: PROJECT_ID
          value: ${PROJECT_ID}
        - name: APPLE_TEAM_ID
          value: ${APPLE_TEAM_ID}
        - name: APPLE_BUNDLE_ID
          value : ${APPLE_BUNDLE_ID}
        - name: APPLE_APNS_KEY_ID
          value : ${APPLE_APNS_KEY_ID}
        - name : APPLE_APNS_KEY
          value : ${APPLE_APNS_KEY}
        - name : KAKAO_REST_API_KEY
          value : ${KAKAO_REST_API_KEY}
        - name : ETCD_IS_AD
          value : false
        - name : ETCD_INTERVAL_AD
          value : 300
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi