name: Deploy to AppEngine Manual

on:
  workflow_dispatch:
    inputs:
      app_name:
        description: 'app name'
        default: 'helloworld'
        required: true
      is_stop_previous_version:
        description: '--no-stop-previous-version'
        default: 'true'
        required: true

env:
  PROJECT_ID: ${{ secrets.PROJECT_ID }}
  APP_NAME: ${{ github.event.inputs.app_name }}
  HOST: ${{ secrets.HOST }}

jobs:
  setup-deploy:
    name: Setup and Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # Setup gcloud CLI
    - uses: google-github-actions/setup-gcloud@v0.2.0
      with:
        service_account_key: ${{ secrets.SA_KEY }}
        project_id: ${{ secrets.PROJECT_ID }}

    # Configure Docker to use the gcloud command-line tool as a credential
    # helper for authentication
    - run: |-
        gcloud --quiet auth configure-docker

    # Deploy - no stop previous version
    - name: Deploy - no stop previous version
      if: ${{ github.event.inputs.is_stop_previous_version == 'true' }}
      run: |-
        cd deployments/${{ env.APP_NAME }}
        sed -i 's/${PROJECT_ID}/${{ env.PROJECT_ID }}/g' app.yaml
        sed -i 's/${HOST}/${{ env.HOST }}/g' app.yaml
        gcloud app deploy --no-stop-previous-version --quiet

    # Deploy - stop previous version
    - name: Deploy - stop previous version
      if: ${{ github.event.inputs.is_stop_previous_version == 'true' }}
      run: |-
        cd deployments/${{ env.APP_NAME }}
        sed -i 's/${PROJECT_ID}/${{ env.PROJECT_ID }}/g' app.yaml
        sed -i 's/${HOST}/${{ env.HOST }}/g' app.yaml
        gcloud app deploy --quiet
