name: Deploy to GCP CloudRun
# todo

on:
  push:
    branches:
      - dev
env:
  APP_ENVIRONMENT: production
  SERVICE_NAME: clubhouse

jobs:
  setup-deploy:
    name: Setup and Deploy
    runs-on: ubuntu-latest

    environment: Clubhouse

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'

    - name: 'Use gcloud CLI'
      run: 'gcloud info'

    # Configure Docker to use the gcloud command-line tool as a credential
    # helper for authentication
    - run: |-
        gcloud --quiet auth configure-docker

    # Deploy - stop previous version
    - name: Deploy - stop previous version
      run: |-
        gcloud builds submit -t gcr.io/${{ secrets.PROJECT_ID }}/${SERVICE_NAME}:${GITHUB_SHA} .
        cat <<EOF >> cloudrun.yaml
        apiVersion: serving.knative.dev/v1
        kind: Service
        metadata:
          name: golf
          annotations:
            run.googleapis.com/ingress: all
        spec:
          template:
            spec:
              containerConcurrency: 80
              timeoutSeconds: 300
              serviceAccountName: golf-367911@appspot.gserviceaccount.com
              containers:
              - image: gcr.io/${{ secrets.PROJECT_ID }}/${SERVICE_NAME}:${GITHUB_SHA}
                ports:
                - name: h2c
                  containerPort: 50051
                env:
                - name: APP_ENVIRONMENT
                  value: ${APP_ENVIRONMENT}
                - name: PROJECT_ID
                  value: ${{ secrets.PROJECT_ID }}
                - name: APPLE_TEAM_ID
                  value: ${{ secrets.APPLE_TEAM_ID }}
                - name: APPLE_BUNDLE_ID
                  value : ${{ secrets.APPLE_BUNDLE_ID }}
                - name: APPLE_APNS_KEY_ID
                  value : ${{ secrets.APPLE_APNS_KEY_ID }}
                - name : APPLE_APNS_KEY
                  value : ${{ secrets.APPLE_APNS_KEY }}
                - name : KAKAO_REST_API_KEY
                  value : ${{ secrets.KAKAO_REST_API_KEY }}
                resources:
                  limits:
                    cpu: 1000m
                    memory: 512Mi
        EOF
        cat cloudrun.yaml
        gcloud run services replace cloudrun.yaml --region=asia-northeast3
