name: Deploy to GCP CloudRun
# todo

on:
  push:
    branches:
      - dev
      # - main
env:
  PROJECT_ID: ${{ secrets.PROJECT_ID }}

jobs:
  setup-deploy:
    name: Setup and Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # Setup gcloud CLI
    - uses: google-github-actions/setup-gcloud@v0.2.0
      with:
        service_account_key: ${{ secrets.SA_KEY }}
        project_id: ${{ secrets.PROJECT_ID }}

    # Configure Docker to use the gcloud command-line tool as a credential
    # helper for authentication
    - run: |-
        gcloud --quiet auth configure-docker

    # Deploy - stop previous version
    - name: Deploy - stop previous version
      run: |-
        gcloud builds submit -t gcr.io/${{ env.PROJECT_ID }}/haru:0.1.32 .
        gcloud run services replace deployments/dev/cloudrun.yaml --region=asia-northeast3
